name: Test Azure OIDC
on:
  push:
    branches: none # [ "main" ]
    paths: 
      - 'azure-oidc.yml'
  pull_request: 
    branches: none  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Az login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    - name: 'Build image in ACR'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.44.0
        inlineScript: |
          az acr build -r ${{ secrets.ARM_ACR_NAME }} -t service:${{ github.sha }} --build-arg API_GIT_HASH=${{ github.sha }} --build-arg http_port=3000  --target production -f service/Dockerfile .
    - name: 'Deploy image'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.ARM_APPS_NAME }}
        images: '${{ secrets.ARM_ACR_NAME }}.azurecr.io/service:${{ github.sha }}'
    - name: AZ logout
      run: |
        az logout